# Site settings
title: "Rafael L. Ventura Blog"
email: rafa.luve@gmail.com
description: "A simple blog of a former graduate designer"
baseurl: ""
url: "http://raffesmind.github.io/"
title_description: ""
title_image: ""
google_analytics: ""
disqus_account:
github_repository: https://github.com/raffesmind
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: _raffesmind
github_username:  raffesmind
linkedin_link: https://br.linkedin.com/in/raffes
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Made with Jekylls and Carte Noire Template by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; Articles by Rafael L. Ventura &copy

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
